# Generated by Django 4.2.1 on 2023-05-10 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksApiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=12, max_digits=15)),
                ('isbn', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='ApiModel',
        ),
    ]
